name: "Cache Poetry Installation"
runs:
  using: "composite"  # <-- this is the important part
  steps:
    - id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: ~/.local  # the path depends on the OS
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenvs-path: ~/.venv
        installer-parallel: true