name: github pages

on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: "3.10"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/cache_poetry_installation
      - name: Install dependencies
        run: poetry install --with docs

      - name: Build sphinx docs
        run: |
          cd docs
          poetry run make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html